package LogServer;

class LogServerFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	String client_string = "";
	String net_client_string = "";
	String server_string = "";

	/** Creates new form LogServerFrame */
	public LogServerFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		clientArea = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		ServerArea = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		NetClientArea = new javax.swing.JTextArea();
		resetButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
		jLabel1.setText("2FAClient");

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
		jLabel2.setText("2FAServer");

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18));
		jLabel3.setText("2FANetworkServer");

		clientArea.setColumns(20);
		clientArea.setEditable(false);
		clientArea.setRows(5);
		jScrollPane1.setViewportView(clientArea);

		ServerArea.setColumns(20);
		ServerArea.setEditable(false);
		ServerArea.setRows(5);
		jScrollPane2.setViewportView(ServerArea);

		NetClientArea.setColumns(20);
		NetClientArea.setEditable(false);
		NetClientArea.setRows(5);
		jScrollPane3.setViewportView(NetClientArea);

		resetButton.setText("Reset");
		resetButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(
										jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 377,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap())
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(127, 127, 127).addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409,
										Short.MAX_VALUE)
								.addComponent(jLabel2).addGap(329, 329, 329).addComponent(jLabel3).addGap(69, 69, 69))
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
								.addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jLabel1).addComponent(jLabel2))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(resetButton)
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetButtonActionPerformed
		this.client_string = "";
		this.net_client_string = "";
		this.server_string = "";

		this.clientArea.setText(this.client_string);
		this.ServerArea.setText(this.server_string);
		this.NetClientArea.setText(this.net_client_string);
	}// GEN-LAST:event_resetButtonActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LogServerFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public javax.swing.JTextArea NetClientArea;
	public javax.swing.JTextArea ServerArea;
	public javax.swing.JTextArea clientArea;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JButton resetButton;
	// End of variables declaration//GEN-END:variables

}
